/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Paneles;

/**
 *
 * @author Aaron
 */
public class Pnl_2 extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Adj
     */
    public Pnl_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpContenedor = new javax.swing.JTabbedPane();
        pnlAdjudicada = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNumCont = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiasEntrega = new javax.swing.JTextField();
        txtLugar = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbtGyR = new javax.swing.JRadioButton();
        rbtPrincipal = new javax.swing.JRadioButton();
        cmbOrdenar = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        rbtFirme = new javax.swing.JRadioButton();
        rbtDuda = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rbtnHabil = new javax.swing.JRadioButton();
        rbtnNat = new javax.swing.JRadioButton();
        cmbEntre = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtEnc = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaObs = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        pnlOrden = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroOrden = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiasE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOrden = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVigCon = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLugarEnt = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        cmbOrden = new javax.swing.JComboBox<>();
        btnModifi = new javax.swing.JButton();
        btnBus = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        btnEli = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        dateFechaLi = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtEnc2 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtaObs1 = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        pnlDemanda = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNOrden = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDes = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNOrdn = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtVig = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtLuEn = new javax.swing.JTextField();
        cmbOrdenado = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        btnAgreg = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnBusc = new javax.swing.JButton();
        btnLimp = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        dateFechaLim = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaObs2 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        txtEnc3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        pnlEntregada = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtOrdenNum = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtDiasEntregar = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtLugarEntrega = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        rbtGyRGrupo = new javax.swing.JRadioButton();
        rbtPrincipalB = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        btnAg = new javax.swing.JButton();
        btnMo = new javax.swing.JButton();
        btnBu = new javax.swing.JButton();
        btnLi = new javax.swing.JButton();
        btnBo = new javax.swing.JButton();
        cmbOrd = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        cmbEnt = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        txtDesc1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        pnlAdjudicada.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("N° Contratación");

        txtNumCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumContActionPerformed(evt);
            }
        });

        jLabel6.setText("Descripción");

        jLabel7.setText("Días de entrega");

        txtLugar.setText("Lugar/Institución");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel9.setText("Empresa");

        rbtGyR.setText("GyR Grupo Asesor");

        rbtPrincipal.setText("Principal Brands");
        rbtPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPrincipalActionPerformed(evt);
            }
        });

        cmbOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número Orden", "Empresa", "Descripción", "Lugar/Institución", "Días de entrega", "Estado" }));
        cmbOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenarActionPerformed(evt);
            }
        });

        jLabel10.setText("Ordenar por");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salvar.png"))); // NOI18N
        btnAgregar.setText("Agregar");

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar-archivo.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        rbtFirme.setText("En firme");

        rbtDuda.setText("En duda");

        jLabel16.setText("Estado");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Contratación", "Empresa", "M Entrega", "Descripción", "Lugar/Institución", "Días de entrega", "Estado", "Encargado", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        rbtnHabil.setText("Hábiles");
        rbtnHabil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHabilActionPerformed(evt);
            }
        });

        rbtnNat.setText("Naturales");

        cmbEntre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Según demanda", "Cantidad definida", "Del 50%", "Parcial" }));
        cmbEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntreActionPerformed(evt);
            }
        });

        jLabel30.setText("Modalidad entrega");

        jLabel32.setText("Encargado");

        txtEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncActionPerformed(evt);
            }
        });

        txtaObs.setColumns(20);
        txtaObs.setRows(5);
        jScrollPane5.setViewportView(txtaObs);

        jLabel34.setText("Observaciones");

        javax.swing.GroupLayout pnlAdjudicadaLayout = new javax.swing.GroupLayout(pnlAdjudicada);
        pnlAdjudicada.setLayout(pnlAdjudicadaLayout);
        pnlAdjudicadaLayout.setHorizontalGroup(
            pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdjudicadaLayout.createSequentialGroup()
                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(cmbEntre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbtGyR)
                                    .addComponent(rbtPrincipal)
                                    .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                                        .addComponent(rbtnHabil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnNat))
                                    .addComponent(txtNumCont, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtDiasEntrega)))))
                    .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLugar)
                    .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdjudicadaLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(38, 38, 38))
                                .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(30, 30, 30)))
                            .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtDuda)
                            .addComponent(rbtFirme)
                            .addComponent(txtDescripcion)
                            .addComponent(jTextField8)
                            .addComponent(txtEnc)
                            .addComponent(cmbOrdenar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addGap(88, 88, 88))
        );
        pnlAdjudicadaLayout.setVerticalGroup(
            pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtLugar)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDiasEntrega, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtFirme)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtDuda)
                        .addGap(17, 17, 17)
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAdjudicadaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnHabil)
                            .addComponent(rbtnNat))
                        .addGap(14, 14, 14)
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtGyR)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtPrincipal)
                        .addGap(8, 8, 8)
                        .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(cmbEntre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdjudicadaLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdjudicadaLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlAdjudicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBorrar)
                    .addComponent(jLabel10)
                    .addComponent(cmbOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpContenedor.addTab("Adjudicada", pnlAdjudicada);

        pnlOrden.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("N° Contratación");

        jLabel2.setText("Descripción");

        jLabel3.setText("Días de entrega");

        jLabel4.setText("N° Orden");

        jLabel11.setText("Vigencia contrato");

        txtVigCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVigConActionPerformed(evt);
            }
        });

        jLabel12.setText("Lugar de entrega");

        txtLugarEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarEntActionPerformed(evt);
            }
        });

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salvar.png"))); // NOI18N
        btnInsertar.setText("Agregar");

        cmbOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número Orden", "Descripción", "Días de entrega", "Orden", "Facturado", "Entregado" }));

        btnModifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnModifi.setText("Modificar");

        btnBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBus.setText("Buscar");

        btnLim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btnLim.setText("Limpiar");

        btnEli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar-archivo.png"))); // NOI18N
        btnEli.setText("Eliminar");

        jLabel17.setText("Ordenar por:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Contratación", "Descripción", "Días de entrega", "V Contrato", "N° Orden", "Fecha límite", "Lugar entrega", "Encargado", "Observaciones"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel31.setText("Fecha límite entrega");

        jLabel33.setText("Encargado");

        txtEnc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnc2ActionPerformed(evt);
            }
        });

        txtaObs1.setColumns(20);
        txtaObs1.setRows(5);
        jScrollPane6.setViewportView(txtaObs1);

        jLabel35.setText("Observaciones");

        javax.swing.GroupLayout pnlOrdenLayout = new javax.swing.GroupLayout(pnlOrden);
        pnlOrden.setLayout(pnlOrdenLayout);
        pnlOrdenLayout.setHorizontalGroup(
            pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiasE, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOrdenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateFechaLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrdenLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtVigCon, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(313, 313, 313)
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35))
                        .addGap(51, 51, 51)
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOrdenLayout.createSequentialGroup()
                                .addComponent(cmbOrden, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
                            .addComponent(txtLugarEnt)
                            .addComponent(txtEnc2)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtOrden))))
                .addGap(80, 80, 80))
            .addGroup(pnlOrdenLayout.createSequentialGroup()
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifi)
                        .addGap(18, 18, 18)
                        .addComponent(btnBus)
                        .addGap(18, 18, 18)
                        .addComponent(btnLim)
                        .addGap(18, 18, 18)
                        .addComponent(btnEli)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlOrdenLayout.setVerticalGroup(
            pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiasE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtLugarEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtVigCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFechaLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(txtEnc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnModifi)
                    .addComponent(btnBus)
                    .addComponent(btnLim)
                    .addComponent(btnEli)
                    .addComponent(jLabel17)
                    .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpContenedor.addTab("Orden", pnlOrden);

        pnlDemanda.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("N° Contratación");

        jLabel14.setText("Descripción");

        jLabel15.setText("Días de entrega");

        jLabel18.setText("N° Orden");

        txtNOrdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOrdnActionPerformed(evt);
            }
        });

        jLabel19.setText("Vigencia contrato");

        jLabel20.setText("Lugar de entrega");

        cmbOrdenado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número Orden", "Descripciún", "Dúas de Entrega", "Orden", "Facturado", "Entregado" }));
        cmbOrdenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenadoActionPerformed(evt);
            }
        });

        jLabel21.setText("Ordenar por:");

        btnAgreg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salvar.png"))); // NOI18N
        btnAgreg.setText("Agregar");

        btnMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnMod.setText("Modificar");

        btnBusc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBusc.setText("Buscar");

        btnLimp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btnLimp.setText("Limpiar");

        btnElim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar-archivo.png"))); // NOI18N
        btnElim.setText("Eliminar");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Contratación", "Descripción", "Días de entrega", "V Contrato", "Fecha límite", "N° Orden", "Lugar entrega", "Encargado", "Observaciones"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel8.setText("Fecha límite entrega");

        txtaObs2.setColumns(20);
        txtaObs2.setRows(5);
        jScrollPane7.setViewportView(txtaObs2);

        jLabel36.setText("Observaciones");

        txtEnc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnc3ActionPerformed(evt);
            }
        });

        jLabel37.setText("Encargado");

        javax.swing.GroupLayout pnlDemandaLayout = new javax.swing.GroupLayout(pnlDemanda);
        pnlDemanda.setLayout(pnlDemandaLayout);
        pnlDemandaLayout.setHorizontalGroup(
            pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDemandaLayout.createSequentialGroup()
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDemandaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlDemandaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateFechaLim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDemandaLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVig))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDemandaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDemandaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEntrega)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(39, 39, 39)
                        .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEnc3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDes)
                                .addComponent(txtNOrdn)
                                .addComponent(txtLuEn)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                        .addGap(81, 81, 81)))
                .addContainerGap())
            .addGroup(pnlDemandaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnAgreg)
                .addGap(18, 18, 18)
                .addComponent(btnMod)
                .addGap(18, 18, 18)
                .addComponent(btnBusc)
                .addGap(18, 18, 18)
                .addComponent(btnLimp)
                .addGap(18, 18, 18)
                .addComponent(btnElim)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbOrdenado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        pnlDemandaLayout.setVerticalGroup(
            pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDemandaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtNOrdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtVig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtLuEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDemandaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateFechaLim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(pnlDemandaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(txtEnc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDemandaLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDemandaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgreg)
                            .addComponent(btnMod)
                            .addComponent(btnBusc)
                            .addComponent(btnLimp)
                            .addComponent(btnElim)
                            .addComponent(jLabel21)
                            .addComponent(cmbOrdenado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpContenedor.addTab("Según demanda", pnlDemanda);

        pnlEntregada.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("N° Contratación");

        txtOrdenNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdenNumActionPerformed(evt);
            }
        });

        jLabel23.setText("Descripción");

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });

        jLabel24.setText("Días de entrega");

        jLabel25.setText("Medio de entrega");

        jLabel26.setText("Lugar de entrega");

        jLabel27.setText("Fecha de entrega");

        rbtGyRGrupo.setText("GyR Grupo Asesor");

        rbtPrincipalB.setText("Principal Brands");

        jLabel28.setText("Empresa");

        btnAg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salvar.png"))); // NOI18N
        btnAg.setText("Agregar");

        btnMo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnMo.setText("Modificar");

        btnBu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBu.setText("Buscar");

        btnLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btnLi.setText("Limpiar");

        btnBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar-archivo.png"))); // NOI18N
        btnBo.setText("Borrar");

        cmbOrd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número Orden", "Empresa", "Descripción", "Días de entrega", "Último día para entrega", "Lugar de entrega", "Fecha de entrega" }));

        jLabel29.setText("Ordenar por:");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Contratación", "Empresa", "Descripción", "Días de entrega", "Lugar de entrega", "Fecha de entrega", "Medio entrega", "Encargado", "Observaciones"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        cmbEnt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Encomienda", "Proveedor", "Encargado" }));

        jLabel38.setText("Encargado");

        txtDesc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesc1ActionPerformed(evt);
            }
        });

        jLabel39.setText("Observaciones");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane8.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlEntregadaLayout = new javax.swing.GroupLayout(pnlEntregada);
        pnlEntregada.setLayout(pnlEntregadaLayout);
        pnlEntregadaLayout.setHorizontalGroup(
            pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntregadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(pnlEntregadaLayout.createSequentialGroup()
                        .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEntregadaLayout.createSequentialGroup()
                                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAg)
                                        .addGroup(pnlEntregadaLayout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addGap(33, 33, 33)
                                            .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbtPrincipalB)
                                                .addComponent(rbtGyRGrupo)))))
                                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEntregadaLayout.createSequentialGroup()
                                        .addGap(388, 388, 388)
                                        .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel38)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel39)))
                                    .addGroup(pnlEntregadaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMo)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBu)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLi)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29))))
                            .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlEntregadaLayout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtLugarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlEntregadaLayout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDiasEntregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(txtOrdenNum, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDesc)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbOrd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDesc1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(cmbEnt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEntregadaLayout.setVerticalGroup(
            pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntregadaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtOrdenNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txtDiasEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtLugarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(txtDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEntregadaLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(27, 27, 27)
                        .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(rbtGyRGrupo)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEntregadaLayout.createSequentialGroup()
                        .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtPrincipalB)
                            .addComponent(cmbEnt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEntregadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAg)
                            .addComponent(btnMo)
                            .addComponent(btnBu)
                            .addComponent(btnLi)
                            .addComponent(btnBo)
                            .addComponent(jLabel29)
                            .addComponent(cmbOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tbpContenedor.addTab("Entregada", pnlEntregada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnHabilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHabilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnHabilActionPerformed

    private void cmbEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEntreActionPerformed

    private void txtVigConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVigConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVigConActionPerformed

    private void rbtPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPrincipalActionPerformed

    private void txtNumContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumContActionPerformed

    private void cmbOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrdenarActionPerformed

    private void txtNOrdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOrdnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOrdnActionPerformed

    private void cmbOrdenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrdenadoActionPerformed

    private void txtLugarEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarEntActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncActionPerformed

    private void txtEnc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnc2ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void txtEnc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnc3ActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void txtOrdenNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdenNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdenNumActionPerformed

    private void txtDesc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesc1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAg;
    private javax.swing.JButton btnAgreg;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBo;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBu;
    private javax.swing.JButton btnBus;
    private javax.swing.JButton btnBusc;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEli;
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLi;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton btnLimp;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMo;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnModifi;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbEnt;
    private javax.swing.JComboBox<String> cmbEntre;
    private javax.swing.JComboBox<String> cmbOrd;
    private javax.swing.JComboBox<String> cmbOrden;
    private javax.swing.JComboBox<String> cmbOrdenado;
    private javax.swing.JComboBox<String> cmbOrdenar;
    private com.toedter.calendar.JDateChooser dateFechaLi;
    private com.toedter.calendar.JDateChooser dateFechaLim;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel pnlAdjudicada;
    private javax.swing.JPanel pnlDemanda;
    private javax.swing.JPanel pnlEntregada;
    private javax.swing.JPanel pnlOrden;
    private javax.swing.JRadioButton rbtDuda;
    private javax.swing.JRadioButton rbtFirme;
    private javax.swing.JRadioButton rbtGyR;
    private javax.swing.JRadioButton rbtGyRGrupo;
    private javax.swing.JRadioButton rbtPrincipal;
    private javax.swing.JRadioButton rbtPrincipalB;
    private javax.swing.JRadioButton rbtnHabil;
    private javax.swing.JRadioButton rbtnNat;
    private javax.swing.JTabbedPane tbpContenedor;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtDesc1;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDiasE;
    private javax.swing.JTextField txtDiasEntrega;
    private javax.swing.JTextField txtDiasEntregar;
    private javax.swing.JTextField txtEnc;
    private javax.swing.JTextField txtEnc2;
    private javax.swing.JTextField txtEnc3;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JTextField txtLuEn;
    private javax.swing.JLabel txtLugar;
    private javax.swing.JTextField txtLugarEnt;
    private javax.swing.JTextField txtLugarEntrega;
    private javax.swing.JTextField txtNOrden;
    private javax.swing.JTextField txtNOrdn;
    private javax.swing.JTextField txtNumCont;
    private javax.swing.JTextField txtNumeroOrden;
    private javax.swing.JTextField txtOrden;
    private javax.swing.JTextField txtOrdenNum;
    private javax.swing.JTextField txtVig;
    private javax.swing.JTextField txtVigCon;
    private javax.swing.JTextArea txtaObs;
    private javax.swing.JTextArea txtaObs1;
    private javax.swing.JTextArea txtaObs2;
    // End of variables declaration//GEN-END:variables
}
